# Generated by Django 4.0.2 on 2022-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
